"use client"

import { Badge } from "@/components/ui/badge"
import { Checkbox } from "@/components/ui/checkbox"
import { MoreVertical, User } from 'lucide-react'
import { Button } from "@/components/ui/button"
import { Eye, Pencil, Trash2 } from 'lucide-react'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"

export const columns = [
  {
    id: "select",
    header: () => (
      <div className="px-1">
      
      </div>
    ),
    cell: () => (
      <div className="px-1"> 
      </div>
    ),
    enableSorting: false,
    enableHiding: false,
  },
  {
    accessorKey: "id",
    header: "ID",
  },
  {
    accessorKey: "generatedBy",
    header: "Generated By",
    cell: ({ row }) => {
      const email = row.getValue("generatedBy")
      return (
        <div className="flex items-center gap-2">
          <User className="h-4 w-4 text-gray-500" />
          {email}
        </div>
      )
    },
  },
  {
    accessorKey: "Date",
    header: "Date",
    cell: ({ row }) => {
      const date = row.getValue("Date")
      return (
        <Badge variant="secondary" className="bg-blue-500/15 border border-blue-500 text-blue-500 px-1.5 py-0.5 text-xs">
          {date}
        </Badge>
      )
    },
  },
  {
    accessorKey: "Type",
    header: "Type",
    cell: ({ row }) => {
      const type = row.getValue("Type")
      return (
        <span className="font-medium text-gray-600">
          {type}
        </span>
      )
    },
  },
  {
    accessorKey: "Content",
    header: "Content",
    cell: ({ row }) => {
      const content = row.getValue("Content")
      return (
        <div className="max-w-[500px] truncate">
          {content}
        </div>
      )
    },
  },
  {
    id: "actions",
    cell: () => {
      return (
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="ghost" size="icon">
              <MoreVertical className="h-4 w-4" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent  align="end">
            <DropdownMenuItem className="text-gray-600">
              <Eye className="mr-2 h-4 w-4" />
              View
            </DropdownMenuItem>
            <DropdownMenuItem className="text-gray-600">
              <Pencil className="mr-2 h-4 w-4" />
              Edit
            </DropdownMenuItem>
            <DropdownMenuItem className="text-red-600">
              <Trash2 className="mr-2 h-4 w-4" />
              Delete
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      )
    },
}
]

